reads_suffix: # suffix of read files
  "fq"
#  "fq.gz"
#  "fastq"
#  "fastq.gz"
#  "fa"
#  "fa.gz"
#  "fasta"
#  "fastq.gz"
time_mode: # time mode of prediction
  "read"
#   "clock"
prediction_sampling: # prediction sampling interval (in seconds)
  60
phylogroup_score_threshold: # threshold on phylogroup score for passing
  0.5
susceptibility_score_threshold: # threshold on susceptibility score for susceptibility
  0.6
