reads_suffix: # suffix of read files
  "fq"
#  "fq.gz"
#  "fastq"
#  "fastq.gz"
#  "fa"
#  "fa.gz"
#  "fasta"
#  "fastq.gz"
time_mode: # time mode of prediction
  "read"
#   "clock"
#   "mimic-ont"
prediction_sampling: # prediction sampling interval (in seconds)
  60
phylogroup_score_threshold: # threshold on phylogroup score for passing
  0.5
susceptibility_score_threshold: # threshold on susceptibility score for susceptibility
  0.6
mimic_ont_mbp_per_minute: # mimic-ont; milions of basepairs per minute
 "1.43"
mimic_ont_datetime: # mimic-ont; date time of the sequencing start
 "2018-01-01 00:00:00"
